### ISSUE TITLE
Sign Up?

### ISSUE THREAD

**Issue by nicno90** [CompSci3-4/HelpDesk-Web#3]
I feel like there needs to be a way for teachers to sign up for this site so we don't have to deal with manually coding each teacher in. Also if a teacher retires it will be easier to deal with removing from a List rather than going through the code, and with new teachers we don't have to manually add them in either. I think this has already been addressed but I will ask tomorrow in class (today is 5/14/15). Just for my own peace of mind I'm also going to say we should add the link to sign up on the Login Page.

**Comment by tomgarcia** [comment]
I've already added registration to the API and I'm adding it the website either tonight or tomorrow.
